### ISSUE TITLE
udpate snap

### ISSUE THREAD

**Issue by ng0177** [plars/stellarium-snap#5]
Much appreciate, if s.o. could look into this [issue](https://github.com/Stellarium/stellarium/issues/1071#issuecomment-622353625) Thanks!

**Comment by t4saha** [comment]
Snap has been Updated. [Both stable (20.1) & edge channel]
https://snapcraft.io/stellarium-daily

**Comment by plars** [comment]
I think this should be working now on my snap, along with a few other fixes.
